### ISSUE TITLE
Content won't download in Editor

### ISSUE THREAD

**Issue by cdhanna** [beamable/BeamableProduct#3149]
context: https://disruptorbeam.slack.com/archives/C19GUHW4D/p1710246609088439

Moe found that he cannot download content in the Editor reliably. He gets timeouts and curl 28 errors all the time. However, he is able to take the URL for the content and download it just fine in the browser.

**Comment by gabrielbeamable** [comment]
Tried to reproduce this problem, but wasn't able to. Talked to @mhijaziB and we are going to schedule some time next week (03/18 - 03/22) to work together on this. For now moving this back to TODO.

**Comment by cdhanna** [comment]
time is scheduled tomorrow to look into this
