### ISSUE TITLE
LightBeam - Toolbox integration

### ISSUE THREAD

**Issue by PedroRauizBeamable** [beamable/BeamableProduct#3150]
![Image](https://github.com/beamable/BeamableProduct/assets/3848374/766aba64-21ff-4586-9651-db4257c3a28b)

These prefab references are going to go away in 2.0, because the prefabs won't exist! 
We should do something with this window, ideally, we should show hints that the light beams exist as samples, and make it easy to add those samples to your project.

Lightbeams are Package samples, and Package samples live in 
/Packages/com.beamable/Samples~

The `package.json` will give us the definitive Samples listings, and where those samples are. So, we would READ the package.json file to drive the content of the toolbox. 

Then, when adding a Sample to the project, we'd need to directory copy/paste from the relative path defined in the `package.json`, into the `/Assets` folder.

We'll keep the UI/UX as similar as possible. Let's use the existing "big giant square button" approach. When you click on a button, we should popup confirming the installation of the sample into the Project. 
Each button should have a triple-dot menu that shows, 
1. open src code
2. open in browser (which would open the link to the docs hosted lightbeam)

**Comment by cdhanna** [comment]
Until we figure out the Lightbeam hosting, this ticket has a decent amount of uncertainty.
