### ISSUE TITLE
AssumeUser should forbid invalid player IDs, especially forbidding 0 as the playerId

### ISSUE THREAD

**Issue by allister-beamable** [beamable/BeamableProduct#3249]
**Describe the bug**
When using `AssumeUser` in C# microservice code, if the `playerId` argument is 0, this can lead to problems when using APIs that involve in-flight messages, such as for example Groups service join/leave requests, the backend encounters errors trying to look up the user whose player ID is 0. As such, `playerId`=0 should be avoided categorically.

**To Reproduce**
```csharp
[ClientCallable, SwaggerCategory("GroupsTests")]
public async Promise<string> TestAssumeUserLeaveGroup(long playerId, long groupId)
{
	var assumed = AssumeUser(playerId, false);
	try
	{
		await assumed.Services.Groups.LeaveGroup(groupId);
		return $"Succeeded with assumed user: {assumed.Context.UserId}";
	}
	catch (Exception e)
	{
		return $"Failed with assumed user: {assumed.Context.UserId}; exception: {e.Message}";
	}
}
```
Invoke this callable from the Swagger docs page in the portal and supply `"playerId": 0`

**Expected behavior**
Call fails with an exception (outside the try/catch) saying that playerId 0 is not valid.

**Actual behavior**
Call succeeds (at least by virtue of the try/catch) and an in-flight message gets created for playerId 0 (only verifiable by backend database access).

**Additional context**
My test that I showed in the repro steps is purposely using the deprecated `AssumeUser` as opposed to `AssumeNewUser`, but both of them should forbid invalid player IDs.

**Comment by allister-beamable** [comment]
Ideally, assuming a user should verify that the player ID is valid for the realm, but that might prove impractical for IDs that are structurally correct and plausible (example: using a group ID in place of a player ID, since they are both 16-digit decimal numbers pulled from the same serial pool) since it would require querying the API.

As such, a minimum viable fix for this would be to simply forbid zero.

**Comment by cdhanna** [comment]
Lets add a check to the `AssumeUser` & `AssumeNewUser` methods that checks the given playerId is positive (strictly greater than zero). If not, throw a well known, `InvalidPlayerIdException` or some such.

**Comment by gabrielbeamable** [comment]
https://github.com/beamable/BeamableProduct/pull/3342
