### ISSUE TITLE
Bursts of WebSocket connection errors, with fast, unbounded recursive loop in `OnClose` handler

### ISSUE THREAD

**Issue by allister-beamable** [beamable/BeamableProduct#3320]
**Describe the bug**
Some Game Makers have observed that occasionally, while working in Unity Editor, a series of many (100+) WebSocket connection errors will appear in the console. They seem to come in bursts: the console will remain quiet for a long while, but then if there is some kind of issue, the error spams the log in the hundreds.

**To Reproduce**
There are no concrete repro steps other than "be working in the Unity Editor for awhile, using a realm that uses WebSockets for communication" (one example of this is enabling `notification|publisher` = "beamable")

**Expected behavior**
WebSockets connections should be vanishingly rare, and when they occur, there should be only one (or at most a small few) error message, and the system should self-heal and recover automatically.

**Actual behavior**
Whenever there are issues, there is a rapid spam of `WebSocketConnectionException: Unable to connect to the remote server`

**Metadata**

- SDK version: 1.19.12 (at time of original Game Maker report; they may have updated to 1.19.17 since then)

**Additional context**

The Game Maker noted that the `OnClose` handler in https://github.com/beamable/BeamableProduct/blob/1.19.17/client/Packages/com.beamable/Runtime/Connection/WebSocketConnection.cs#L139-L162 appears to be leading to an infinite loop, since the `_disconnecting` value is false when these bursts of errors occur, and remains false throughout the process.

**Comment by cdhanna** [comment]
Adding some exponential back off would be a good middle ground step here.
