### ISSUE TITLE
CLI - beam init should use --save-to-file by default

### ISSUE THREAD

**Issue by gabrielbeamable** [beamable/BeamableProduct#3328]
The `beam init` command has a `--save-to-file` command that is opt-in, but we want to change it so that it becomes the default behaviour. Instead, there should be a flag, `--no-token-save` that prevents the token from saving to disk.

Bug:

With the latest CLI, follow the steps:

1. Create a new folder and execute `beam init --host=dev` in the CLI inside it
2. After loging in with your credentials, create a new service by executing `beam project new service <NAME>`
3. Try running the service by executing `beam project run --ids <NAME>`
4. Observe that an error related to a refresh token will happen
5. Execute `echo $BEAM_ENV` in the CLI
6. Observe that it's empty

The variable `$BEAM_ENV` should have all the data necessary for the microservice to be able to run. This is probably the reason why errors are happening when trying to run SAMS.

![Image](https://github.com/beamable/BeamableProduct/assets/141041673/417b1714-802b-4702-834a-dee13939cc8b)

**Comment by cdhanna** [comment]
test this again after --save-to-file becomes the default.
