### ISSUE TITLE
Implicit beamo manifest files

### ISSUE THREAD

**Issue by cdhanna** [beamable/BeamableProduct#3350]
```json
    "ServiceDefinitions": [
        {
            "BeamoId": "NotifTest",
            "Protocol": 0,
            "DependsOnBeamoIds": [],
            "ImageId": "",
            "ShouldBeEnabledOnRemote": true,
            "TruncImageId": ""
        }
    ],
```

`BeamoId` could be 
1. csproj file name, folder name, assembly name, "whatever the user typed when they said microservice create"

**Comment by cdhanna** [comment]
Here is the full manifest snippet for a local service, only.

```json
{
    "ServiceDefinitions": [
        {
            "BeamoId": "NotifTest",
            "Protocol": 0,
            "DependsOnBeamoIds": [],
            "ImageId": "",
            "ShouldBeEnabledOnRemote": true,
            "TruncImageId": ""
        }
    ],
    "HttpMicroserviceLocalProtocols": {
        "NotifTest": {
            "DockerBuildContextPath": "services",
            "RelativeDockerfilePath": "NotifTest/Dockerfile",
            "BindSrcForHotReloading": {
                "IsReadOnly": false,
                "LocalPath": null,
                "InContainerPath": null
            },
            "HotReloadEnabledEndpoint": null,
            "HotReloadEnabledPort": null,
            "CustomPortBindings": [],
            "CustomBindMounts": [],
            "CustomVolumes": [],
            "CustomEnvironmentVariables": [],
            "InstanceCount": 1
        }
    },
    "HttpMicroserviceRemoteProtocols": {
        "NotifTest": {
            "HealthCheckEndpoint": "health",
            "HealthCheckPort": "6565",
            "CustomEnvironmentVariables": []
        }
    },
    "EmbeddedMongoDbLocalProtocols": {},
    "EmbeddedMongoDbRemoteProtocols": {}
}
```

Thinking about the `ServiceDefinitions` blob, 

|field | comment |
| - | - |
| `BeamoId` | could be the msbuild property defined in the csproj, or coalesce to the assembly name |
| `Protocol` | inferfed from detecting a `csproj` file referencing the `Beamable.Microservices.Runtime` nuget package |
| `DependsOnBeamoIds` | this is no longer necessary anymore, I think its not supposed to be in the JSON at all. |
| `ImageId` | this refers to the image you'd deploy if you were going to deploy it. From a CLI workflow perspective, I don't think we need to put this here at all, see later comment about deployments |
| `ShouldBeEnabledOnRemote` | see comment on deployments |
| `TruncImageId` | see comment on deployments |

Thinking about the `HttpMicroserviceLocalProtocols` blob
|field |comment|
| - | - |
| (key) `NotifTest` | this comes from the same logic as the `BeamoId` |
| `DockerBuildContextPath` | we _could_ infer this as the folder path containing the `.beamable/` folder. This way, the _entire_ beam context is part of the docker context. I'm not sure if there are docker related reasons to NOT have a giant build context.|
| `RelativeDockerfilePath` | if we infer the `DockerBuildContextPath`, we'd just need to constrain the `Dockerfile` to live next to the `csproj` file, which feels like a _mostly_ safe idea. |
| `BindSrcForHotReloading` | Honestly, I think now that we can use dotnet watch without docker, we could simplify our lives by REMOVING hot reload with volumes inside docker. This way, docker builds would become mirrors of production releases |
| `HotReloadEnabledEndpoint` | remove |
| `HotReloadEnabledPort` | remove |
| `CustomPortBindings` | remove |
| `CustomBindMounts` | remove |
| `CustomEnvironmentVariables` | remove |
| `InstanceCount` | remove |

Thinking about the `HttpMicroserviceRemoteProtocols` blob, honestly, I think we could hardcode all these properties. The idea that they are definable is _cool_, but it feels like premature optimization at this point. We have no use cases where these values AREN'T "health" and `6565`. When we _do_, we can revisit. 


----

There are some properties from the `ServiceDefinitions` blob that are about _deployment_ only. When you do `beam services deploy` or `beam services run`, you are making a "deployment" either on the remote-realm, or your local docker service. In these cases, the services that turn on need to be defined _somewhere_. When you do `beam services deploy`, what you're really doing is pushing docker images to Beamable, and then POSTing a manifest file containing the service names, docker image ids, and enabled booleans. 

This is the trickiest part to "infer", because the very nature of the use case is that the developer is SETTING values. 

Perhaps, we should dramatically change the UX around doing deployments and local docker runs. 

```sh
# deploy a beamo-schema manifest
beam services deploy --manifest=<path-to-manifest>
```

The above would be cool, and it would let us redeploy old manifests if they existed as json files.
However, it doesn't answer how the manifest is generated if its the first deployment, or if the developer is modifying enablement or service-sizing (something we _still_ don't support :cry: ).

A deployment is 2 major steps.
1. upload docker images to Beamable,
2. upload manifest file

I think we should separate these steps into separate commands.

```sh 
# build, health-check, and upload service docker images. The result of this command produces the imageIds as a JSON blob.
beam services upload --ids=<filter>
```

```json
{
    "uploads": {
        "NotifTest": {
            "imageId": "1234", 
            "success": true,
        }
    }
}
```

Then, separately, 
```sh
beam services manifest new --output="./path.json"
# scans for projects, and requests imageId, and enabled value. 
# if there are remote instances of the service, it can inherit those values.

# the result of this command is a manifest file
```


```sh
beam services manifest push --manifest=<path>
```


```sh
# a combination of beam services upload, and beam services manifest
beam services deploy 
```


Use cases for deployment

0. I want to deploy something for the first time
```sh
beam services deploy

# with no given --manifest flag, this defaults to declaring an implicit manifest from what is already deployed, and
#  merging in new services as enabled. 
# This then runs `beam services upload`, and `beam services manifest push` with the latest imageId variants
```

1. I want to update my services with the latest code.
```sh
beam services deploy
```

2. I want to change which services are enabled.
```sh
beam services manifest new --output=next.json
# edit next.json
beam services deploy --manifest=next.json 
```

3. I want to delete a service.
```sh
rm -rf NotifTest/
beam services deploy
```

4. I want to add a service.
```sh
beam project new service AnotherTuna 
beam services deploy
```

5. I want to roll services.
```sh
beam services manifest current --output=current.json
beam services manifest push --manifest=specific.json
```

6. I want to get an old deployment, and make a tweak to it.
```sh
beam services manifest get --filter=<?>
# edit specific manifest somehow
beam services manifest push --manifest=specific.json
```

6. I want to deploy the services to a local docker instance and see what happens
```sh
beam services run 
```

7. I want to deploy the services, with a specific manifest.
```sh
beam services run --manifest=specific.json

#if the source code for a service does not exist locally, this command will currently fail, but there is possibility that
#  we could add remote image download
```

**Comment by cdhanna** [comment]
docker build context defaults to .beamable folder root, _but_ can be overridden not at the per project level, but at the per workspace level. 

_config-defaults.json_
```json
{
 // relative to parent of .beamable folder.
 "relative-docker-build-context": "."
}
```

**Comment by cdhanna** [comment]
open questions that cause uncertainty- 
1. how do we read the csproj files?
2. is it possible to sub-filter the tarball for the docker build image command?

**Comment by cdhanna** [comment]
part of this is being done by https://github.com/beamable/BeamableProduct/issues/3270

**Comment by PedroRauizBeamable** [comment]
Quick research:
- There seems to be a csproj parser from microsoft in this MS nuget package: `Microsoft.Build.Utilities.Core`.
- It seems to allow edits (which might come in handy in case we want CLI commands to write stuff to csprojs --- migration flows and all that).
