### ISSUE TITLE
Docs USAM - Unity getting update of different beamable projects

### ISSUE THREAD

**Issue by cdhanna** [beamable/BeamableProduct#3378]
Unity project is running `beam project ps -w` to observe SAM updates, 

Two Unity projects with the same CID/PID but different local SAM developments cause each Unity project to receive the updates for BOTH SAMs, including the one that isn't part of the current Unity project. 

The Unity project may log (verbose logging, specifically) stuff from a SAM in another project

```
/UnityProjectA
  /.beamable
  /serverices
     /A
/UnityProjectB
  /.beamable
  /services
     /B
```

The goal here is to document that this is actually "fine", and can be ignored. The docs should explain that the commands show CId/Pid based information, NOT folder based information.

**Comment by gabrielbeamable** [comment]
The gist that I wrote for this:
https://gist.github.com/gabrielbeamable/d8e6ef1dff4092ddda36b0a476bd56c6
