### ISSUE TITLE
Requester should expose `Date:` header from HTTP response, as a source of server-authoritative time

### ISSUE THREAD

**Issue by allister-beamable** [beamable/BeamableProduct#3395]
**Is your feature request related to a problem? Please describe.**

At present if a Game Maker wants to get authoritative server time, they have to implement a C# Microservice method that uses `DateTime.UtcNow` or something equivalent. However, every HTTP response from the Beamable backend includes a `Date:` header that could be used as a source of authoritative server time (assuming the server-to-client latency is small enough to be negligible).

**Describe the solution you'd like**

It would be nice to have a way to directly query `Requester` for the server time reported by the most recent API response. Ideally, this should be anchored to device time in some way. That is, it should allow me to answer two questions:
* "What time was it on the server when that response got sent to me?"
* "How much did device time differ from the server time when we received that response?"

**Describe alternatives you've considered**

While it is possible to work around this issue by implementing my own `[ClientCallable]public Promise<string> GetServerTime()` or the like, that is non-ideal for a couple of reasons: first off it requires me to have a C#MS at all (I might want an otherwise client-oriented game that doesn't use C#MS), and secondly it adds unnecessary network round trips to get information that already exists.

**Comment by cdhanna** [comment]
in the `HandleResponse` function of the `PlatformRequester`, we could do something like this, 
```csharp
if (request.GetResponseHeaders().TryGetValue("Date", out var dateHeader))
{
	// unknown format of dateHeader
}
```

**Comment by allister-beamable** [comment]
Here is an example of the response headers:
```bash
amacleod@valjean ~/s/e/AllisterTest> http POST https://api.beamable.com/basic/auth/token X-BEAM-SCOPE:$CID.$PID grant_type=guest
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 155
Content-Type: application/json
Date: Tue, 21 May 2024 13:42:05 GMT
Server: akka-http/10.1.15
```

**Comment by cdhanna** [comment]
the Date header result from proto-actor may be different!

**Comment by cdhanna** [comment]
We should reach out to Justin and ask if we can change the header result for Date

**Comment by allister-beamable** [comment]
> the Date header result from proto-actor may be different!

I did a quick check and it was the same as from the main stack: `<DoW>, DD <Mon> YYYY HH:MM:SS GMT`

There is probably not a huge amount of leeway in changing the output, unless we want to break compliance with HTTP standards (https://www.rfc-editor.org/rfc/rfc7231#section-7.1.1.1). It is a crying shame it cannot be ISO 8601 (https://xkcd.com/1179/), but specs gonna specify.

**Comment by cdhanna** [comment]
hint, line 606 in `PlatformRequester` could extract header like this,
```csharp

if (request.GetResponseHeaders().TryGetValue("Date", out var dateHeader))
{
	
}
```
