### ISSUE TITLE
CLI - create service not updating sdk version correctly after it's creation in IDE

### ISSUE THREAD

**Issue by gabrielbeamable** [beamable/BeamableProduct#3468]
(this is happening after changes on the way we load manifest information from csproj files)
While debugging using Rider, if you try creating a service, in the part where it changes the SDK version in the service's csproj file, it fails with the following message:

```
/usr/local/share/dotnet/sdk/8.0.204/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.props(14,3): error MSB4244: The SDK resolver assembly "/usr/local/share/dotnet/sdk/8.0.204/Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.dll" could not be loaded. An attempt was made to load a program with an incorrect format. [/Users/gabrielramos/Projects/BeamableProduct/client/Assets/Beamable/StandaloneMicroservices~/K/K.csproj]
/usr/local/share/dotnet/sdk/8.0.204/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.props(14,3): error MSB4244:  (0x8007000B) [/Users/gabrielramos/Projects/BeamableProduct/client/Assets/Beamable/StandaloneMicroservices~/K/K.csproj]
Unable to create dependency graph file for project '/Users/gabrielramos/Projects/BeamableProduct/client/Assets/Beamable/StandaloneMicroservices~/K/K.csproj'. Cannot add package reference.
```

The command being executed through the CLI is this one:
`dotnet add "Assets/Beamable/StandaloneMicroservices~/K" package Beamable.Microservice.Runtime --version "0.0.123"`

and if you try running it in terminal, it works fine. Also, when Unity try to create a new service it just works as well. SO this is something specifically to the IDE.

A few things that were already attempted at this:
 - Adding a `global.json` file to the `client` folder with the correct dotnet version
 - Removing some extra environment variables to test if it was something with that
 - checked if the IDE was trying to execute the process in a different working directory
 - checked if dotnet executable used was the same in all cases

**Comment by cdhanna** [comment]
this was caused by a bad dotnet 8.0.5 version.
