### ISSUE TITLE
USAM - don't let unity write over already existing services in the sln

### ISSUE THREAD

**Issue by gabrielbeamable** [beamable/BeamableProduct#3479]
Scan through existing projects, if it exists in it's folder and also in the sln file, let it be in there, don't remove it.

This logic would live in this method: `OnGeneratedSlnSolution`

**Comment by cdhanna** [comment]
calling out from Gabriel; this cannot be avoided for the first time the project is loaded after fresh install. But, that is an acceptable level of sln flickering.
