### ISSUE TITLE
User is stuck when attempting to play microservice

### ISSUE THREAD

**Issue by BeamDwayne** [beamable/BeamableProduct#3491]
User is unable to run a microservice. Attempting to click Play button only gives the user an infinite loading experience.

Note/s:
I have difficulty running a microservice from past versions, but now fresh accounts or existing accounts does not let me play the microservice at all.

1. Launch Editor
2. Install RC build
3. Register/Login
4. Go to Microservices Manager
5. Create a Microservice > Play the microservice

**Expected behavior**
Microservice must play

**Actual behavior**
User is only stuck on an infinite loading attempting to play the microservice

**Screenshots**
![does_not_completely_play](https://github.com/beamable/BeamableProduct/assets/100598975/c8b21d13-b100-4384-9b14-516400db2a7e)

**Metadata**
Build Details:
1.19.21-PREVIEW.RC2
2022.310f1
Windows 10

**Comment by cdhanna** [comment]
tested, not a real issue
