### ISSUE TITLE
1.19.21 Blocker - User is unable to publish a microservice

### ISSUE THREAD

**Issue by BeamDwayne** [beamable/BeamableProduct#3492]
Publishing a microservice only lets the user get stuck on loading.

Note/s:
Used Existing and New accounts
Previous RC versions had me attempt multiple times in order to publish, but on this current version, I cannot Publish at all

1. Launch Editor
2. Install RC build
3. Login/Register
4. Go to Microservices Manager
5. Create Microservice
6. Publish Microservice

**Expected behavior**
User must be able to publish without issues

**Actual behavior**
User is stuck on publish microservice loading screen

**Screenshots**
![cannot_publish_microservice](https://github.com/beamable/BeamableProduct/assets/100598975/15f889e0-c5fe-4ab3-b45e-cc0bb1edf89b)

**Metadata**
1.19.21-PREVIEW.RC2
2022.310f1
Windows 10

**Comment by cdhanna** [comment]
tested, not a real issue
