### ISSUE TITLE
CLI - services coming back to life after deploy

### ISSUE THREAD

**Issue by gabrielbeamable** [beamable/BeamableProduct#3493]
- Have 1 or more services deployed to your realm
- delete those services locally
- Go to the portal and stop and archive all of those services
- Create a new service
- Deploy that service
- Notice that all services previously archived, are now unarchived, but still stopped

They don't exist locally and I checked and their ShouldBeEnabledOnRemote  property is set to false as it should. However after the deploy, they all come back to life. Going to create an issue for this.

**Comment by cdhanna** [comment]
This is likely because we aren't passing the `archived` flag along in the manifest, in the `WriteServiceManifestFromLocal` method.

**Comment by cdhanna** [comment]
new deploy fixed this.
