### ISSUE TITLE
NoConnectivityException should carry info about its cause

### ISSUE THREAD

**Issue by allister-beamable** [beamable/BeamableProduct#3495]
## Is your feature request related to a problem? Please describe.

When game builds are "in the wild" sometimes issues may occur that include or coincide with a `NoConnectivityException`. Since `NoConnectivityException` can happen in a few different contexts and with a few different underlying causes, it would be great to have a way to tell from the stack-trace _AND_ any corresponding log message what relevant information pertains to the connectivity exception.

## Describe the solution you'd like

The stack-trace and corresponding log messages for every `NoConnectivityException` should contain information about where and how the exception originated:
 - There should be short, clear keywords showing whether the cause was HTTP response code 0, an underlying `UnityWebRequester` exception, a different exception, or any other potential cause for NCE
 - There should be short, clear keywords showing _where_ the exception happened. For example, an exception during token refreshing may be different from an exception in the OfflineCache, which may in turn be different from an exception on a routine API call; if this domain can be subdivided into 3-5 "sectors" (or whatever makes sense given the patterns of usage) that would help guide diagnosis efforts.

These keywords should be visible to, and easy to interpret by, both Game Makers and Beamable staff. Additionally, if they end up surfaced in a player-facing context, they should be reasonably easy for players to explain to Game Makers when the players contact customer support.

**Comment by cdhanna** [comment]
we want to know which requests generate the exception, where they come from, if they're coming from socket errors,

**Comment by gabrielbeamable** [comment]
Make sure all of the information we are adding is actually added to the exception that is going to be logged in the console.

**Comment by gabrielbeamable** [comment]
Do the low hanging fruits one, get the easiest information we can get and show to Allister, to see if that is enough.
