### ISSUE TITLE
USAM - editor window not updating correctly after service is has errored

### ISSUE THREAD

**Issue by gabrielbeamable** [beamable/BeamableProduct#3510]
This happens some times while creating a new service, just keeps frozen like in the screenshot and don't update:

![Image](https://github.com/beamable/BeamableProduct/assets/141041673/0c10abab-8d68-41d6-82f8-22fb2e2b858c)

**Comment by cdhanna** [comment]
under the hood, an error has happened, but we aren't surfacing the error, and the UI is stuck in the middle.
