### ISSUE TITLE
CLI - Add a validation for `.config/dotnet-tools.json`

### ISSUE THREAD

**Issue by gabrielbeamable** [beamable/BeamableProduct#3511]
1 - Check for the existence of this file
 2 - Check that the version of the CLI is the same that the one in the config json file
 3 - Change the version in the config json file to the one it's supposed to be and log it happened at the end

The command that should be used to change the version is the `beam version set ...` (yet to be done) and we should tell people to use that instead of changing manually the file.

**Comment by gabrielbeamable** [comment]
This depends on #3505

**Comment by cdhanna** [comment]
I don't think we need to do this anymore given the advent of the redirect stuff and the `beam version install` command. 

`version install` _does_ the stuff that `version set` is talking about.
And we already get validation messages if the listed version is different than the execution version.
