### ISSUE TITLE
Allow content-is-changed override in custom, per-developer code

### ISSUE THREAD

**Issue by allister-beamable** [beamable/BeamableProduct#3512]
### Is your feature request related to a problem? Please describe.

Sometimes the function that detects whether a Beamable Content entry (such as for determining which content entries should be included in a publish, and to show the blue "changed" badge in Content Manager) gets confused by data structures that might be functionally the same but lead to a different checksum. In the past, this has occurred for Beamable built-in content that includes schedules, since the `cron` expression can be mutated structurally while keeping the same semantic meaning. In cases like that, it would be nice to selectively suppress the "is changed" predicate.

### Describe the solution you'd like

As a Game Maker, in order to control the changed-nature of content entries my team is authoring, I would like to create a custom, in-house function that overrides the "is this content entry changed?" decision. If I could override some kind of `IsContentChanged(ContentRef theContent /* ... maybe some other context, too? ... */)` function using dependency injection, that would be great.

### Describe alternatives you've considered

At present, no alternatives seem to be available short of forking and modifying the Beamable SDK wholesale.

**Comment by cdhanna** [comment]
a more refined "inner" problem....
We shouldn't be changing content without user input. If it wasn't changing, then users wouldn't see modified content.... and then the described problem never appears in the first place.

**Comment by cdhanna** [comment]
another helpful tool would be a difftool....

**Comment by cdhanna** [comment]
Customers can hurt themselves by writing content like this that sets values in field initializers, or inside callback methods.


```csharp

	[ContentType("silly")]
	public class SillyContent : ContentObject, ISerializationCallbackReceiver
	{
		public int x = 3;

		private string timeStr;
		public DateTime time = DateTime.Today;

		public void OnBeforeSerialize()
		{
			timeStr = time.ToLongTimeString();
		}

		public void OnAfterDeserialize()
		{
			time = DateTime.Parse(timeStr);
			x = 5;
		}
	}
```

**Comment by cdhanna** [comment]
this can happen if there is an array/list, and the elements change order.

**Comment by allister-beamable** [comment]
With the tiniest tinge of sadness/misgivings, closing this in favor of #3573 

(for the record, my misgivings are that, even with a diff tool as described in 3573 there may be situations where a Game Maker's implementation of a particular piece of custom content are _so unusual_ that they merit an is-changed override; maybe that is a fake concern, but it is something that cannot be solved by visibility tools)
