### ISSUE TITLE
Unexpected "Uncheck" tooltip on Publish Content dialog

### ISSUE THREAD

**Issue by allister-beamable** [beamable/BeamableProduct#3519]
### Describe the bug

Publishing content from Content Manager is meant to be all-or-nothing. Either I publish all the changes I have, or I cancel the publication so I can make more changes before I really publish. However, the "Publish Content" dialog has tooltips on the checkmark icons next to individual items that imply that those checkmarks can be unchecked. Nothing happens when you click the checkmark, so the tooltip is misleading.

![Screenshot 2024-07-02 at 10 05 21](https://github.com/beamable/BeamableProduct/assets/71026539/2106ca20-66e1-4dfc-9703-309007a2afcc)

### To Reproduce

Go to Content Manager and press Publish whenever you have at least one changed content entry.

Hover over the rounded checkmark icon next to one of the changed items.

### Expected behavior

There is no tooltip. The icon is just an icon.

### Actual behavior

A tooltip saying "Uncheck" appears, implying that one could uncheck the checkmark icon. However, nothing happens when you click the icon.

### Metadata

Please include,
- SDK version: 1.19.21
- Engine version: Unity 2021.3.27f1
- Operating System: macOS (Intel)

**Comment by cdhanna** [comment]
this may be a "default" tooltip from Unity, which means if you CTRL+F for "Uncheck", you'll be outta-luck.
