### ISSUE TITLE
CLI - deploying local microservices is mutating remote microservices

### ISSUE THREAD

**Issue by gabrielbeamable** [beamable/BeamableProduct#3565]
Copy paste slack message from Ali (https://disruptorbeam.slack.com/archives/C03P1J5NR97/p1722463507844239):

There's a bug with the CLI when deploying microservices that aren't available locally.
Scenario:

- I have Microservice "MyService" and Microstorage "MyStorage" locally
- I also have in the realm, deployed remotely, a federated microservice "YourMicroservice" and microstorage "YourMicrostorage" (which depend on each other)
- If I go to deploy "MyService" and "MyStorage", it will happily keep "YourMicroservice" and "YourMicrostorage" in the realm (which is good)

However, it will also break the dependencies (i.e. YourMicroservice depends on YourMicrostorage) in the published manifest as well as the federation, by essentially setting the components field to an empty array.
This is problematic, because it shouldn't be mutating remote microservices when deploying local microservices.

**Comment by gabrielbeamable** [comment]
We need to investigate how much of this is a client side issue of deployments and how much is a backend issue (if there is any). Also talk with some backend folks to get a better grasp of how deployment works on the backend side.

**Comment by allister-beamable** [comment]
My understanding of how C#MS deployment works in this context is roughly:
1. Prepare everything it can (build local Docker images, etc.)
2. Fetch manifest from remote.
3. Create new manifest from local state plus info from step 2.
4. Upload images from step 1.
5. Upload merged manifest from step 3.

So my question is, what do the manifests look like in step 2 and step 3? Is the backend giving enough information in the downloaded manifest for local to make a valid manifest in step 3?
