### ISSUE TITLE
[CLI QA] "beam services run" command returns an error when used

### ISSUE THREAD

**Issue by BeamDwayne** [beamable/BeamableProduct#3594]
Description:
User cannot proceed into CLI QA tests after using command:
"beam services run"
---
Issue blocks me from proceeding onto the next steps

**To Reproduce**

1. in a new workspace, "beam init" should work and create a .beamable folder
2. in an existing workspace, "beam init" should overwrite existing .beamable folder
3. in an existing workspace, "beam project new service test1"  should create a SAM
4. Copy BeamableServices in the same folder and rename it as test.sln
5. in an existing workspace, "beam project new service test2 --sln test.sln" create a new SAM project in the existing sln
6. in an existing workspace, "beam project new common-lib test_lib" should work
7. in an existing workspace, "beam project new storage test_str" should work
8. beam project new service test3
9. test that a SAM can be run via "beam services run"

**Expected behavior**
Microservices should run after calling the command

**Actual behavior**
User is prompted by an error after using the said command

**Screenshots**
![beam_services_run](https://github.com/user-attachments/assets/95b0eb31-6988-4fcc-86c3-f0e2d993c2c3)

**Metadata**
CLI 2.1.0 RC2
Windows 10

**Comment by cdhanna** [comment]
Gabriel pointed out that there may be a hidden "root-cause" issue that spawned the log issue.

**Comment by cdhanna** [comment]
The filepath is decided by this property...
`public string TempLogFilePath => Path.Combine(Path.GetTempPath(), "beamCliLog.txt");`

**Comment by cdhanna** [comment]
We need to offer software that doesn't explode and hide errors.
Also important (but less important) is to not bloat people's machines. 

So with that stack rank of objectives, we should just have multiple log files (one per CLI invocation).

**Comment by cdhanna** [comment]
we should
1. move the logs to the .beamable/temp/logs folder
2. if the path isn't resolvable, then revert to no logs and say, "re-run with --logs v"
3. add a `beam temp clear logs` that clears logs folder in temp

**Comment by cdhanna** [comment]
when we fix the log issue; also just try to do the `beam services run` and make sure it works; or discover the true inner error that lurked all along.
