### ISSUE TITLE
USAM - On startup keeps installing Dotnet on Windows

### ISSUE THREAD

**Issue by Leinnan** [beamable/BeamableProduct#3605]
When I try to open Beamable Unity project on Windows it keeps reloading with information about installing Dotnet.

**Comment by cdhanna** [comment]
Peter had the wrong patch version

**Comment by cdhanna** [comment]
First step is to enable unit test runners on windows & mac on Github Actions. 
Hopefully we can reproduce the error on GH. If we can't then we should add a specific test that does reproduce it on GH. 
We may need to specifically replicate a version of
1. windows
2. with a specific dotnet version
Then we should fix it such that the tests pass
