### ISSUE TITLE
Failed to refresh account in Unity Editor when access token has expired

### ISSUE THREAD

**Issue by allister-beamable** [beamable/BeamableProduct#3617]
### Describe the Bug

When the access token for a developer in Unity Editor has passed its 10-day expiration, the SDK fails to fully initialize and prints a bunch of errors in the console, including `Failed to refresh account` and `Exception: Service not found IPlatformService`. It is possible to solve this by logging out and logging back in, but this is not an ideal user experience.

### Steps to reproduce

1. Log into a Beamable project in Unity Editor
2. Close your computer and walk away for 11+ days (or have unlucky timing where the 10-day refresh falls on a long weekend or something)
3. Reopen the project in Unity
4. Try to do anything that requires Beamable backend access (such as downloading content)

#### Expected behavior

- the SDK is able to get a new access token using the stored refresh token
- API access works after the token refresh sequence automatically occurs

#### Actual behavior

- between receiving the 401 Access Denied due to expired token and trying to refresh the token, there is an exception that prevents the token refresh sequence from happening

### Metadata

- SDK Version: 1.19.22

### Additional information

When this situation occurs, developers can resolve it by using Beamable Toolbox to log out and log back in again.

The refresh failure only seems to occur rarely, such as when a developer goes on vacation or other circumstances that lead them to leave the project aside for multiple days; chances are that when developers are interacting with the SDK on a regular workday basis, the SDK is able to preemptively refresh the token _before_ it actually fully expires.

**Comment by allister-beamable** [comment]
When stepping through in a debugger, we found that the exception was thrown when PlatformRequester tries to resolve IPlatformService via dependency injection: https://github.com/beamable/BeamableProduct/blob/1.19.22/client/Packages/com.beamable/Runtime/Core/Platform/SDK/PlatformRequester.cs#L423

**Comment by cdhanna** [comment]
The exception is being thrown from code that is shared between Runtime and Editor. The Runtime properly fills out a Dependency Injectable scope; but the Editor does not. When this error pathway happens in the Editor, the Editor tries to use DI to resolve a dependency that has not been registered. 

Instead of using the `IPlatformService`, we should use the `IUserContext`, and implement the `IUserContext` on the `Beamable.Editor.AccountService` (which is where the editor account info is stored), and then inject the `IUserContext` into the `BeamEditor` DI scope.

**Comment by Leinnan** [comment]
In order to reproduce it I changed this code in `AccessTokenStorage`:
![Image](https://github.com/user-attachments/assets/2d6f8c02-4865-49d7-b84d-6f5e8459d897)
