### ISSUE TITLE
CLI 3 blocker - update scheduler SDK to use new headers

### ISSUE THREAD

**Issue by cdhanna** [beamable/BeamableProduct#3658]
the scheduler needs to use the same routingKey header when specifying local C#MS callbacks. This removes the prefix injection in the url.

**Comment by cdhanna** [comment]
@jstnlef  does this have a JIRA ticket associated with it for the API change to the scheduler, to include headers?

**Comment by jstnlef** [comment]
The work is associated with this ticket https://disruptorbeam.atlassian.net/browse/PLAT-5668
