### ISSUE TITLE
[CLI] Commands hang if the connection-auth.json has the wrong token

### ISSUE THREAD

**Issue by dpatekar** [beamable/BeamableProduct#3776]
**Describe the bug**
CLI version 2.0.2
Every CLI command hangs if the connection-auth.json has the wrong token.

**To Reproduce**
Change to a different realm.

**Expected behavior**
Error message OR ask for new credentials.

**Actual behavior**
Hangs trying to fetch a token and beamo manifest in a loop (found that using Fiddler to capture CLI's traffic)

**Metadata**
Env:
- CLI 2.0.2
- Windows

**Comment by cdhanna** [comment]
I think this has already been fixed in the 3.0 RC7 
<img width="1463" alt="image" src="https://github.com/user-attachments/assets/007cdb9e-0ebc-4525-bea6-6db4d78b0852">
